syntax: scss
extends:
  - stylelint-config-recommended-scss
  - stylelint-config-recess-order
rules:
  rule-empty-line-before:
    - always
    - except: first-nested
  block-no-empty: null
  property-no-vendor-prefix: null
  value-no-vendor-prefix:
    - true
    - ignoreValues:
        - grid
        - fill-available
  value-keyword-case:
    - lower
  selector-pseudo-element-colon-notation: single
